proxies:
proxy-groups:
  - name: üéØDratVPNüáÆüá©
    type: select
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - AUTO-PINGüöÄ
      - AUTO-LISTüìå
      - LOADBALANCE‚ôªÔ∏è
      - MANUALüîë
      - DIRECT
  - name: MANUALüîë
    type: select
    url: http://www.gstatic.com/generate_204
    interval: 300
    use:
      - Opok
      - XOpok
      - XXOpok
      - Opok2
      - XOpok2
      - XXOpok2
      - Basic
      - XBasic
      - XXBasic
      - Basic2
      - XBasic2
      - XXBasic2
      - Vidio
      - XVidio
      - XXVidio
      - Vidio2
      - XVidio2
      - XXVidio2
      - Game
      - XGame
      - XXGame
      - Game2
      - XGame2
      - XXGame2
  - name: FLEXüí¨
    type: select
    proxies:
      - DIRECT
      - üéØDratVPNüáÆüá©
  - name: ADSüõ°
    type: select
    proxies:
      - REJECT
      - üéØDratVPNüáÆüá©
  - name: üîêDW+
    type: select
    proxies:
      - REJECT
      - üéØDratVPNüáÆüá©
  - name: AUTO-PINGüöÄ
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    use:
      - Opok
      - XOpok
      - XXOpok
      - Opok2
      - XOpok2
      - XXOpok2
      - Basic
      - XBasic
      - XXBasic
      - Basic2
      - XBasic2
      - XXBasic2
      - Vidio
      - XVidio
      - XXVidio
      - Vidio2
      - XVidio2
      - XXVidio2
      - Game
      - XGame
      - XXGame
      - Game2
      - XGame2
      - XXGame2
  - name: AUTO-LISTüìå
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    use:
      - Opok
      - XOpok
      - XXOpok
      - Opok2
      - XOpok2
      - XXOpok2
      - Basic
      - XBasic
      - XXBasic
      - Basic2
      - XBasic2
      - XXBasic2
      - Vidio
      - XVidio
      - XXVidio
      - Vidio2
      - XVidio2
      - XXVidio2
      - Game
      - XGame
      - XXGame
      - Game2
      - XGame2
      - XXGame2
  - name: LOADBALANCE‚ôªÔ∏è
    type: load-balance
    strategy: round-robin
    url: http://www.gstatic.com/generate_204
    interval: 300
    lazy: true
    proxies:
      - AUTO-PINGüöÄ
      - AUTO-LISTüìå
proxy-providers:
  Opok:
    type: http
    behavior: classical
    path: "./proxy_provider/axs_3169/opok.yaml"
    url:  https://raw.githubusercontent.com/dratx1/DratVPN/main/proxy_provider/axs_3169/opok.yaml
    interval: 200
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Opok2:
    type: http
    behavior: classical
    path: "./proxy_provider/axs_3169/opok2.yaml"
    url:  https://raw.githubusercontent.com/dratx1/DratVPN/main/proxy_provider/axs_3169/opok2.yaml
    interval: 200
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Basic:
    type: http
    behavior: classical
    path: "./proxy_provider/axs_3169/basic.yaml"
    url:  https://raw.githubusercontent.com/dratx1/DratVPN/main/proxy_provider/axs_3169/basic.yaml
    interval: 200
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Basic2:
    type: http
    behavior: classical
    path: "./proxy_provider/axs_3169/basic2.yaml"
    url:  https://raw.githubusercontent.com/dratx1/DratVPN/main/proxy_provider/axs_3169/basic2.yaml
    interval: 200
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Game:
    type: http
    behavior: classical
    path: "./proxy_provider/axs_3169/game.yaml"
    url:  https://raw.githubusercontent.com/dratx1/DratVPN/main/proxy_provider/axs_3169/game.yaml
    interval: 200
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Game2:
    type: http
    behavior: classical
    path: "./proxy_provider/axs_3169/game2.yaml"
    url:  https://raw.githubusercontent.com/dratx1/DratVPN/main/proxy_provider/axs_3169/game2.yaml
    interval: 200
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Vidio:
    type: http
    behavior: classical
    path: "./proxy_provider/axs_3169/vidio.yaml"
    url:  https://raw.githubusercontent.com/dratx1/DratVPN/main/proxy_provider/axs_3169/vidio.yaml
    interval: 200
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Vidio2:
    type: http
    behavior: classical
    path: "./proxy_provider/axs_3169/vidio2.yaml"
    url:  https://raw.githubusercontent.com/dratx1/DratVPN/main/proxy_provider/axs_3169/vidio2.yaml
    interval: 200
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
#-------------------------------------------------------
  XOpok:
    type: http
    behavior: classical
    path: "./proxy_provider/axs_5546/opok.yaml"
    url:  https://raw.githubusercontent.com/dratx1/DratVPN/main/proxy_provider/axs_5546/opok.yaml
    interval: 200
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  XOpok2:
    type: http
    behavior: classical
    path: "./proxy_provider/axs_5546/opok2.yaml"
    url:  https://raw.githubusercontent.com/dratx1/DratVPN/main/proxy_provider/axs_5546/opok2.yaml
    interval: 200
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  XBasic:
    type: http
    behavior: classical
    path: "./proxy_provider/axs_5546/basic.yaml"
    url:  https://raw.githubusercontent.com/dratx1/DratVPN/main/proxy_provider/axs_5546/basic.yaml
    interval: 200
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  XBasic2:
    type: http
    behavior: classical
    path: "./proxy_provider/axs_5546/basic2.yaml"
    url:  https://raw.githubusercontent.com/dratx1/DratVPN/main/proxy_provider/axs_5546/basic2.yaml
    interval: 200
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  XGame:
    type: http
    behavior: classical
    path: "./proxy_provider/axs_5546/game.yaml"
    url:  https://raw.githubusercontent.com/dratx1/DratVPN/main/proxy_provider/axs_5546/game.yaml
    interval: 200
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  XGame2:
    type: http
    behavior: classical
    path: "./proxy_provider/axs_5546/game2.yaml"
    url:  https://raw.githubusercontent.com/dratx1/DratVPN/main/proxy_provider/axs_5546/game2.yaml
    interval: 200
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  XVidio:
    type: http
    behavior: classical
    path: "./proxy_provider/axs_5546/vidio.yaml"
    url:  https://raw.githubusercontent.com/dratx1/DratVPN/main/proxy_provider/axs_5546/vidio.yaml
    interval: 200
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  XVidio2:
    type: http
    behavior: classical
    path: "./proxy_provider/axs_5546/vidio2.yaml"
    url:  https://raw.githubusercontent.com/dratx1/DratVPN/main/proxy_provider/axs_5546/vidio2.yaml
    interval: 200
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
#-------------------------------------------------------
  XXOpok:
    type: http
    behavior: classical
    path: "./proxy_provider/free/opok.yaml"
    url:  https://raw.githubusercontent.com/dratx1/DratVPN/main/proxy_provider/free/opok.yaml
    interval: 200
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  XXOpok2:
    type: http
    behavior: classical
    path: "./proxy_provider/free/opok2.yaml"
    url:  https://raw.githubusercontent.com/dratx1/DratVPN/main/proxy_provider/free/opok2.yaml
    interval: 200
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  XXBasic:
    type: http
    behavior: classical
    path: "./proxy_provider/free/basic.yaml"
    url:  https://raw.githubusercontent.com/dratx1/DratVPN/main/proxy_provider/free/basic.yaml
    interval: 200
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  XXBasic2:
    type: http
    behavior: classical
    path: "./proxy_provider/free/basic2.yaml"
    url:  https://raw.githubusercontent.com/dratx1/DratVPN/main/proxy_provider/free/basic2.yaml
    interval: 200
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  XXGame:
    type: http
    behavior: classical
    path: "./proxy_provider/free/game.yaml"
    url:  https://raw.githubusercontent.com/dratx1/DratVPN/main/proxy_provider/free/game.yaml
    interval: 200
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  XXGame2:
    type: http
    behavior: classical
    path: "./proxy_provider/free/game2.yaml"
    url:  https://raw.githubusercontent.com/dratx1/DratVPN/main/proxy_provider/free/game2.yaml
    interval: 200
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  XXVidio:
    type: http
    behavior: classical
    path: "./proxy_provider/free/vidio.yaml"
    url:  https://raw.githubusercontent.com/dratx1/DratVPN/main/proxy_provider/free/vidio.yaml
    interval: 200
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  XXVidio2:
    type: http
    behavior: classical
    path: "./proxy_provider/free/vidio2.yaml"
    url:  https://raw.githubusercontent.com/dratx1/DratVPN/main/proxy_provider/free/vidio2.yaml
    interval: 200
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
rule-providers:
  BlockADS:
    type: http
    behavior: classical
    path: "./rule_provider/rule_blockads.yaml"
    url: https://raw.githubusercontent.com/dratx1/DratVPN/main/rule_provider/rule_blockads.yaml
    interval: 86300
  Direct:
    type: http
    behavior: classical
    path: "./rule_provider/rule_direct.yaml"
    url: https://raw.githubusercontent.com/dratx1/DratVPN/main/rule_provider/rule_direct.yaml
    interval: 86300
  Line:
    type: http
    behavior: domain
    path: "./rule_provider/rule_line.yaml"
    url: https://raw.githubusercontent.com/dratx1/DratVPN/main/rule_provider/rule_line.yaml
    interval: 86300
  Porn:
    type: http
    behavior: domain
    path: "./rule_provider/rule_porn.yaml"
    url: https://raw.githubusercontent.com/dratx1/DratVPN/main/rule_provider/rule_porn.yaml
    interval: 86300
  Porn2:
    type: http
    behavior: classical
    path: "./rule_provider/rule_porn2.yaml"
    url: https://raw.githubusercontent.com/dratx1/DratVPN/main/rule_provider/rule_porn2.yaml
    interval: 86300
  Reject:
    type: http
    behavior: domain
    path: "./rule_provider/rule_reject.yaml"
    url: https://raw.githubusercontent.com/dratx1/DratVPN/main/rule_provider/rule_reject.yaml
    interval: 86300
  WhatsApp:
    type: http
    behavior: classical
    path: "./rule_provider/rule_whatsapp.yaml"
    url: https://raw.githubusercontent.com/dratx1/DratVPN/main/rule_provider/rule_whatsapp.yaml
    interval: 86300
rules:
  - GEOSITE,CATEGORY-ADS-ALL,ADSüõ°
  - RULE-SET,BlockADS,ADSüõ°
  - RULE-SET,Direct,DIRECT
  - RULE-SET,Line,FLEXüí¨
  - RULE-SET,Porn,üîêDW+
  - RULE-SET,Porn2,üîêDW+
  - RULE-SET,Reject,üîêDW+
  - RULE-SET,WhatsApp,FLEXüí¨
  - IP-CIDR,127.0.0.1/32,REJECT,no-resolve
  - IP-CIDR6,::1/128,REJECT,no-resolve
  - DST-PORT,7895,REJECT
  - DST-PORT,7892,REJECT
  - DST-PORT,22,DIRECT
  - MATCH,üéØDratVPNüáÆüá©
